name: Build SOPSoft RED APK
on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true 
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2' # Versión estable y compatible

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Flet
        run: |
          pip install flet

      - name: Build APK
        run: |
          # Usamos 'yes' para aceptar licencias y 'release' para optimizar la APK
          yes | flet build apk --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SOPSoft-Red-V4.7.3
          path: build/apk/*.apk